server:
  port: 8081

logging:
  level:
    root: INFO
    com:
      brillianceinfotech: DEBUG

spring:
  application:
    name: REGISTER-SERVICE
  config:
    import: configserver:http://localhost:9296
  datasource:
    url: jdbc:mariadb://localhost:3307/dev1
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: info



